name: "Pet Decay (Testing)"

on:
  schedule:
    - cron: '*/1 * * * *'    # runs every minute
  workflow_dispatch:        # manual trigger

jobs:
  decay:
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger decay loop every 15s (4 iterations)"
        run: |
          # Replace <YOUR_BACKEND_URL> with your actual endpoint
          BACKEND_URL="https://islandpet-backend.onrender.com/decay"
          for i in {1..4}; do
            echo "📡 [Iteration $i] POST $BACKEND_URL"
            curl -X POST "$BACKEND_URL"
            sleep 15
          done
